==================
``101-matrix_mul``
==================

``matrix_mul()`` matrix x matrix.
::
>>> lazy_matrix_mul = __import__("101-lazy_matrix_mul").lazy_matrix_mul
>>> print(lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]]))
[[ 7 10]
 [15 22]]

>>> lazy_matrix_mul([[1, 2], [3, 4]], [[5, 6, 7], [8, 9, 10]])
array([[21, 24, 27],
       [47, 54, 61]])
------------------------------------------------------------
>>> lazy_matrix_mul([[1, 5, 7]], [[3], [5], [8]])
array([[84]])

------------------------------------------------------------
>>> lazy_matrix_mul(2, [1, 2])
Traceback (most recent call last):
    ...
ValueError: Scalar operands are not allowed, use '*' instead

------------------------------------------------------------
>>> lazy_matrix_mul([1, 2], 790)
Traceback (most recent call last):
    ...
ValueError: Scalar operands are not allowed, use '*' instead

------------------------------------------------------------

	>>> print(lazy_matrix_mul([[8.2, 2.4], [2.3, 5.4]], [[0.3, 10.0], [3.1, 7.7]]))
	[[  9.9  100.48]
	 [ 17.43  64.58]]

	>>> print(lazy_matrix_mul([[11.2, 10], [23, 0]], [[0.34, 20], [2.2, 4]]))
	[[ 25.808 264.   ]
	 [  7.82  460.   ]]

	>>> lazy_matrix_mul([], [])
	0.0

	>>> lazy_matrix_mul([[], []], [[], []])
	Traceback (most recent call last):
	ValueError: shapes (2,0) and (2,0) not aligned: 0 (dim 1) != 2 (dim 0)

	>>> lazy_matrix_mul([[]], [[]])
	Traceback (most recent call last):
	ValueError: shapes (1,0) and (1,0) not aligned: 0 (dim 1) != 1 (dim 0)

	>>> lazy_matrix_mul([['1', '2'], ['3', 4]], [["22", "10"], ["BB", "3.1416"]])
	Traceback (most recent call last):
	TypeError: invalid data type for einsum

	>>> lazy_matrix_mul([[1, 2], [3, 4]], [[22, "10"], ["BB", 3.1416]])
	Traceback (most recent call last):
	TypeError: invalid data type for einsum

	>>> lazy_matrix_mul([1, 2, 3, 4], [[22, 10], [6, 36]])
	Traceback (most recent call last):
	ValueError: shapes (4,) and (2,2) not aligned: 4 (dim 0) != 2 (dim 0)

	>>> lazy_matrix_mul([[1, 2], [3, 4]], [22, 10, 23, 3.1416])
	Traceback (most recent call last):
	ValueError: shapes (2,2) and (4,) not aligned: 2 (dim 1) != 4 (dim 0)

	>>> lazy_matrix_mul([[1, 2], [3, 4, 23], [5, 6]], [[22, 10], [0, 16]])
	Traceback (most recent call last):
	ValueError: setting an array element with a sequence.

	>>> lazy_matrix_mul([[1, 2], [3, 4], [5, 6]], [[22, 10], [1], [0, 16]])
	Traceback (most recent call last):
	ValueError: setting an array element with a sequence.

	>>> lazy_matrix_mul([[3, 4], [5, 6]], [[1, 4], []])
	Traceback (most recent call last):
	ValueError: setting an array element with a sequence.

	>>> lazy_matrix_mul(((1, 2), (3, 4), (5, 6)), [[22, 10], [0, 16]])
	array([[ 22,  42],
               [ 66,  94],
               [110, 146]])

	>>> lazy_matrix_mul([[1, 2], [3, 4], [5, 6]], "[[22, 10], [1], [0, 16]]")
	Traceback (most recent call last):
	ValueError: Scalar operands are not allowed, use '*' instead

	>>> lazy_matrix_mul(88, 98)
	Traceback (most recent call last):
	ValueError: Scalar operands are not allowed, use '*' instead

	>>> lazy_matrix_mul()
	Traceback (most recent call last):
	TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'

	>>> lazy_matrix_mul([[1, 2], [3, 4]])
	Traceback (most recent call last):
	TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'

	>>> lazy_matrix_mul([[1, 2, 3], [2, 4, 6]], [[2, 4, 6], [2, 3, 5], [5, 10, 15], [20, 15, 30]])
	Traceback (most recent call last):
	ValueError: shapes (2,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)
